- name: select database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "select * from information_schema.SCHEMATA where schema_name='{{keystone_db_name}}';"|grep -w {{keystone_db_name}}
  ignore_errors: yes
  register: info
  run_once: true

- name: Create the keystone database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "CREATE DATABASE {{keystone_db_name}};"
  ignore_errors: yes
  when: info.rc != 0
  run_once: true

- name: Grant proper access to the keystone database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "GRANT ALL PRIVILEGES ON {{keystone_db_name}}.* TO '{{keystone_db_user}}'@'{{item}}' IDENTIFIED BY '{{keystond_db_password}}';"
  with_items:
    - localhost
    - "%"
  run_once: true

- name: Populate the Identity service database
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone 
  run_once: true
